# IBVS Configuration File

# Maximum number of iterations for the servoing loop
max_iterations: 6

# Path to target image
target_image_path: "/home/khw/Documents/6dpose/dummy_tgt.JPG"

# Time step for control loop (seconds)
dt: 0.005

# Gain parameter for control
K: 20

# Constant forward velocity when keypoints fail to match
constant_forward_vel: 2.5

# Directory to save output files
# TOOD:
save_dir: "/home/khw/Documents/6dpose/TheLanding"

# Directory to save historical RGB images
historical_rgb_path: "/home/khw/Documents/6dpose/TheLanding/Historical_RGB"

# Maximum number of historical masks to keep in queue
historical_mask_queue: 5

# Scale factors for robot control velocities (translational)
x_scale: 10.0
y_scale: 10.0
z_scale: 10.0

# Scale factors for robot control velocities (rotational)
rx_scale: 10.0
ry_scale: 10.0
rz_scale: 10.0
