#!/usr/bin/env python3
"""
Plot the distribution of poses from a text file.

This script loads poses from a text file and creates visualization plots
similar to those generated by generate_poses_lhs.py.

Usage:
    python src/plot_poses_distribution.py poses_lhs_50.txt
"""

import argparse
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt


def load_poses(file_path: str) -> np.ndarray:
    """
    Load poses from a text file.
    
    Parameters
    ----------
    file_path : str
        Path to the poses file
        
    Returns
    -------
    np.ndarray
        Array of poses (n_samples x 6) with columns [x, y, z, roll, pitch, yaw]
    """
    poses = []
    with open(file_path, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip empty lines and comments
            if not line or line.startswith('#'):
                continue
            # Parse pose data
            parts = line.split()
            if len(parts) == 6:
                pose = [float(p) for p in parts]
                poses.append(pose)
    
    if not poses:
        raise ValueError(f"No valid pose data found in {file_path}")
    
    return np.array(poses)


def visualize_distribution(poses: np.ndarray, output_dir: Path):
    """
    Create visualization plots of the pose distribution.
    
    Parameters
    ----------
    poses : np.ndarray
        Array of poses (n_samples x 6)
    output_dir : Path
        Directory to save plots
    """
    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)
    
    labels = ['x (m)', 'y (m)', 'z (m)', 'roll (rad)', 'pitch (rad)', 'yaw (rad)']
    
    # 1. Histograms for each dimension
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    fig.suptitle('Latin Hypercube Sampling - Univariate Distributions', fontsize=14)
    
    for i, (ax, label) in enumerate(zip(axes.flat, labels)):
        ax.hist(poses[:, i], bins=20, edgecolor='black', alpha=0.7)
        ax.set_xlabel(label)
        ax.set_ylabel('Frequency')
        ax.set_title(f'{label} Distribution')
        ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    hist_path = output_dir / 'lhs_distributions.png'
    plt.savefig(hist_path, dpi=150, bbox_inches='tight')
    print(f"✓ Saved histogram plot: {hist_path}")
    plt.close()
    
    # 2. 2D scatter plots for position (x, y, z)
    fig = plt.figure(figsize=(15, 5))
    
    # x-y plane
    ax1 = fig.add_subplot(131)
    ax1.scatter(poses[:, 0], poses[:, 1], alpha=0.5, s=20)
    ax1.set_xlabel('x (m)')
    ax1.set_ylabel('y (m)')
    ax1.set_title('Position: X-Y Plane')
    ax1.grid(True, alpha=0.3)
    ax1.axis('equal')
    
    # x-z plane
    ax2 = fig.add_subplot(132)
    ax2.scatter(poses[:, 0], poses[:, 2], alpha=0.5, s=20)
    ax2.set_xlabel('x (m)')
    ax2.set_ylabel('z (m)')
    ax2.set_title('Position: X-Z Plane')
    ax2.grid(True, alpha=0.3)
    
    # y-z plane
    ax3 = fig.add_subplot(133)
    ax3.scatter(poses[:, 1], poses[:, 2], alpha=0.5, s=20)
    ax3.set_xlabel('y (m)')
    ax3.set_ylabel('z (m)')
    ax3.set_title('Position: Y-Z Plane')
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    scatter_path = output_dir / 'lhs_position_scatter.png'
    plt.savefig(scatter_path, dpi=150, bbox_inches='tight')
    print(f"✓ Saved scatter plot: {scatter_path}")
    plt.close()
    
    # 3. 2D scatter plots for orientation
    fig = plt.figure(figsize=(15, 5))
    
    # roll-pitch
    ax1 = fig.add_subplot(131)
    ax1.scatter(poses[:, 3], poses[:, 4], alpha=0.5, s=20)
    ax1.set_xlabel('roll (rad)')
    ax1.set_ylabel('pitch (rad)')
    ax1.set_title('Orientation: Roll-Pitch')
    ax1.grid(True, alpha=0.3)
    ax1.axis('equal')
    
    # roll-yaw
    ax2 = fig.add_subplot(132)
    ax2.scatter(poses[:, 3], poses[:, 5], alpha=0.5, s=20)
    ax2.set_xlabel('roll (rad)')
    ax2.set_ylabel('yaw (rad)')
    ax2.set_title('Orientation: Roll-Yaw')
    ax2.grid(True, alpha=0.3)
    
    # pitch-yaw
    ax3 = fig.add_subplot(133)
    ax3.scatter(poses[:, 4], poses[:, 5], alpha=0.5, s=20)
    ax3.set_xlabel('pitch (rad)')
    ax3.set_ylabel('yaw (rad)')
    ax3.set_title('Orientation: Pitch-Yaw')
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    orient_path = output_dir / 'lhs_orientation_scatter.png'
    plt.savefig(orient_path, dpi=150, bbox_inches='tight')
    print(f"✓ Saved orientation plot: {orient_path}")
    plt.close()


def print_statistics(poses: np.ndarray):
    """Print statistics about the poses."""
    labels = ['x', 'y', 'z', 'roll', 'pitch', 'yaw']
    units = ['m', 'm', 'm', 'rad', 'rad', 'rad']
    
    print("\n" + "="*70)
    print("POSES STATISTICS")
    print("="*70)
    print(f"{'Parameter':<10} {'Min':>10} {'Max':>10} {'Mean':>10} {'Std':>10} {'Unit':>6}")
    print("-"*70)
    
    for i, (label, unit) in enumerate(zip(labels, units)):
        col = poses[:, i]
        print(f"{label:<10} {col.min():10.5f} {col.max():10.5f} "
              f"{col.mean():10.5f} {col.std():10.5f} {unit:>6}")
    
    print("="*70)


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description='Plot the distribution of poses from a text file',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('poses_file', type=str,
                        help='Path to the poses file')
    parser.add_argument('-o', '--output-dir', type=str, default=None,
                        help='Output directory for plots (default: {poses_file}_viz)')
    
    args = parser.parse_args()
    
    poses_file = Path(args.poses_file)
    if not poses_file.exists():
        print(f"Error: File not found: {poses_file}")
        return 1
    
    # Determine output directory
    if args.output_dir is None:
        output_dir = poses_file.parent / f"{poses_file.stem}_viz"
    else:
        output_dir = Path(args.output_dir)
    
    print("="*70)
    print("PLOTTING POSE DISTRIBUTION")
    print("="*70)
    print(f"Input file: {poses_file}")
    print(f"Output directory: {output_dir}")
    print("="*70)
    
    # Load poses
    print(f"\nLoading poses from {poses_file}...")
    poses = load_poses(str(poses_file))
    print(f"✓ Loaded {len(poses)} poses")
    
    # Print statistics
    print_statistics(poses)
    
    # Generate visualizations
    print("\nGenerating visualization plots...")
    visualize_distribution(poses, output_dir)
    
    print("\n" + "="*70)
    print("PLOTTING COMPLETE")
    print("="*70)
    print(f"Plots saved to: {output_dir}")
    print("="*70 + "\n")
    
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
